### ISSUE TITLE
jsonb.asciidoc improvements

### ISSUE THREAD

**Issue by jefrajames** [eclipse/microprofile-graphql#120]
It would be nice to detail how **@JsonbTransient** and **@GraphQLIgnore** annotations relate together. As far as I understand, there are some overlap between them. They both enable to ignore a field.

Same for **@Name** and **@JsonProperty** which both enable to name a field in the schema.

**Comment by andymc12** [comment]
Thanks for opening this issue @jefrajames! 

`@JsonbTransient` and `@Ignore` are basically interchangeable.  The reason for the `@Ignore` annotation is so that users could choose not to depend on JSON-B APIs.  Similarly, if a user already has JSON-B annotations, then there is no need to add `@Ignore`.

This is the same with `@Name` and `@JsonbProperty`.

I'll add some clarification on this into the spec text.
