### ISSUE TITLE
Add support for Bean Validation

### ISSUE THREAD

**Issue by t1** [eclipse/microprofile-graphql#210]
It would be very convenient, if mutators would check input objects using `jakarta.validation:jakarta.validation-api`. To a lesser extent, the same would be helpful for parameters used in queries.

To be more consistent with JAX-RS, the validation should only be executed, if the bean/parameter is annotated as `@Valid`.

**Comment by andymc12** [comment]
We've discussed this in the one of the weekly meetings (see https://docs.google.com/document/d/1gb3jirFGrJwDZSbrtnFPVTNjPNe3Y0dUYfm-HkU1c3U/edit#bookmark=kix.quas6iia2q5h ).  The net of that conversation was that implementations should be free to support Bean Validation, but that it would not be officially supported in MP GraphQL because the MicroProfile umbrella project does not include BV.  

<soapbox>Personally, I've always that MP should include BV, as it is pretty useful. I [proposed that we include it for MP 2.0](https://groups.google.com/d/msg/microprofile/9hjTySQDutA/w3bFWzU2AAAJ), but it didn't gain enough traction.</soapbox> Maybe we could restart those discussions?

But in the mean time, I would not want to add dependencies in the API to things outside of MP.

Thanks for opening this!

**Comment by t1** [comment]
@andymc12 Thanks for the feedback. I'll try to include it into SmallRye, then.

Good point about the dependencies. Would it be possible to make this an optional dependency?

**Comment by phillip-kruger** [comment]
Hi @t1 - We should be able to support this in SmallRye, even without a dependency on BV, as we can just use the classname in Jandex. If you are keen you can look to add it there ?
