### ISSUE TITLE
@FieldsOrder and @InputFieldsOrder still valid?

### ISSUE THREAD

**Issue by jefrajames** [eclipse/microprofile-graphql#23]
After discussion with @kaqqao, it seems that field ordering is no longer implemented by graphql-java v12. Does it make sense to keep these 2 annotations in the spec in these conditions? graphql-java is considered as the GraphQL RI in the Java ecosystem. If it doesn't implement field ordering will it ever exist?

**Comment by andymc12** [comment]
I'm fine with dropping those annotations for now. I don't think the field order in the schema is all that valuable anyway - at least in most cases, tooling (like GraphiQL, etc.) will parse it, so the order shouldn't matter so much.

If it turns out that I'm wrong, and field order is important, we could always bring these annotations back in a future version of MP GraphQL.

**Comment by kaqqao** [comment]
I also agree with that. If we deem it important in the future, I'm certain we can approach the graphql-java team about supporting it.

**Comment by andymc12** [comment]
Ordering was pulled from GraphQL-java 12, but will be back in 13, so we should be able to implement it.
