### ISSUE TITLE
Endpoint in nested war not discovered

### ISSUE THREAD

**Issue by knives85** [eclipse/microprofile-graphql#350]
Hi all, I'm trying to integrate mpGraphql in my microprofile project but I'm facing a problem. I have a multimodule maven project where the module that is deployed in OpenLiberty has the module with the @GraphQlAPI annotated class as a dependency.

The application is deployed correctly but the graphql schema is not available in this configuration. Everything works fine if I move the Endpoint in the top level module.

Can you help me understand what I'm doing wrong?

Thanks in advance.

**Comment by phillip-kruger** [comment]
Hi @knives85 - might be better to ask on the OpenLiberty Forum.

**Comment by andymc12** [comment]
> Hi @knives85 - might be better to ask on the OpenLiberty Forum.

Agreed.  It looks like you might be running into [this issue](https://github.com/OpenLiberty/open-liberty/issues/14650) which was fixed in [Open Liberty 20.0.0.12](https://openliberty.io/blog/2020/11/20/JNDI-gRPC-200012.html).  If you still see this problem in 20.0.0.12, please open an issue at https://github.com/OpenLiberty/open-liberty/issues

Thanks!
