### ISSUE TITLE
Subscription operation type is missing

### ISSUE THREAD

**Issue by Kenzku** [eclipse/microprofile-graphql#530]
Hej,

I was looking for references in MicroProfile to implement subscription operation on GraphQL, but I could not find the `@Subscription` or similar. 

<img width="451" alt="Screenshot 2023-08-05 at 12 38 11" src="https://github.com/eclipse/microprofile-graphql/assets/1387249/ec53885d-4e33-4e57-89fe-0b3f3747d8d9">

Based on the GraphQL org, the subscription is also a type of operations. Could you please advise, any alternative that can implement subscription operations using MicroProfile? If possible, could you provide a tutorial via https://openliberty.io/guide as well? 

> The operation type is either query, mutation, or subscription and describes what type of operation you're intending to do. The operation type is required unless you're using the query shorthand syntax, in which case you can't supply a name or variable definitions for your operation.

Ref: https://graphql.org/learn/queries/#operation-name

**Comment by andymc12** [comment]
Hi @Kenzku ,

Subscription support was always part of the plan for MicroProfile GraphQL, but never got into the APIs - see issue #174.  It looks like subscriptions are implemented in SmallRye GraphQL (one of the implementations of MP GraphQL) - see https://smallrye.io/smallrye-graphql/2.3.0/typesafe-client-reactive-types/ and https://github.com/smallrye/smallrye-graphql/blob/main/server/api/src/main/java/io/smallrye/graphql/api/Subscription.java.    

Open Liberty packages SmallRye GraphQL as the implementation of MP GraphQL, but I'm not sure what version it packages or whether subscriptions are supported out-of-the-box.  For Open Liberty tutorial requests, please open an issue at https://github.com/OpenLiberty/guides-common/issues.

Since the MP GraphQL community has an issue for subscription support (#174), and since the rest of the request is specific to implementations and/or packagers of MP GraphQL, I will close this issue.  This is in no way an indictment of the request.  Thanks for brining it up.

Hope this helps,
Andy
