### ISSUE TITLE
`enum` types

### ISSUE THREAD

**Issue by andymc12** [eclipse/microprofile-graphql#80]
Java `enum` types need to be converted to GraphQL `enum` types in the schema - and then fields using those types should be made into custom scalars.

This seems to work out of the box for me, but should be documented and tested appropriately in the TCK.

**Comment by phillip-kruger** [comment]
Yes, we need to check all of these features we get out of the box because of graphql-java and spqr and think of how a new implementation will compare if it only implements the spec. I think there is more features we need to document, spec and tck.
For instance, we do not have a Long scalar in the spec, however there is one defined in graphql-java.

**Comment by andymc12** [comment]
> Yes, we need to check all of these features we get out of the box because of graphql-java and spqr and think of how a new implementation will compare if it only implements the spec. I think there is more features we need to document, spec and tck.

Agreed - if you find any please open issues for them so that we can decide whether we want those features in the spec, and if so to properly document/test them.

> For instance, we do not have a Long scalar in the spec, however there is one defined in graphql-java.

Good catch - I opened issue #81 to address this.
