### ISSUE TITLE
Bean validation clarification in the Spec

### ISSUE THREAD

**Issue by phillip-kruger** [eclipse/microprofile-graphql#86]
From our meeting notes :

BeanValidation (@NonNull, @NonEmpty , @Blank → required tag (“!”) in schema) - just on the Schema (!) - what about group parameter ? (ignore for now ?)

**Comment by Emily-Jiang** [comment]
Is there a dependency on Bean Validation from this spec?

**Comment by phillip-kruger** [comment]
Hi @Emily-Jiang . No there is not. But if the user is using bean validation, we will support it.

**Comment by phillip-kruger** [comment]
In microprofile-graphql/spec/target/generated-docs/microprofile-graphql.html#_non_nullable_fields

Should we document (and add a test to TCK) the optional Bean Validation support ?

And what is optional ? @NotNull, @NotEmpty, and @NotBlank ?

**Comment by andymc12** [comment]
Was the consensus that we should make a field non-optional (adding the `!` in the schema) if the Java field is annotated with `@NotNull`, etc.?  

At one point, I thought there was a concern that a field/param/etc. could be annotated with `@NotNull` (from bean validation), but bean validation was not enabled, and then in that case the user's desire was that the field would be considered optional.  

Certainly the safe approach for us would be to not mention bean validation at all - in that case, the schema would indicate that a field was optional when in fact it might actually fail at runtime if the client does not provide a value.  But in that case, the user also has the option to add the GraphQL API `@NonNull` to the field/param/etc. to get the desired result.

If we are going to support bean validation annotations, then I think that `@NotNull` and `@NotEmpty` should result in a non-optional field/argument in the schema.  According to [this article](https://www.baeldung.com/java-bean-validation-not-null-empty-blank), it sounds like `@NotBlank` will allow null values, just not whitespace-only values.

I think I am personally leaning against mentioning support for bean validation now.  My main reason is that if we would support it for `@NotNull`, `@NotEmpty`, etc., it makes me think we ought to support it for other annotations too like `@Size`, `@Future`, etc. - for example, suppose somebody has a query method like:
```
@Query
public Collection<Record> allRecordsWithAtLeastOneSearchTerm(@NotEmpty List<String> searchTerms) { ...

@Query
public Collection<Record> allRecordsWithAtLeastTwoSearchTerms(@NotEmpty @Size(min="2") List<String> searchTerms) { ...
```

If we partially support bean validation, we would then create a schema where both query's  `searchTerms` argument is non-optional, but if the client provides a singletonList<String> to both queries, it will succeed GraphQL input validation on both queries, but fail at runtime when attempting to invoke the second method.  This was the scenario we were hoping to avoid by supporting `@NotNull`, `@NotEmpty`, etc.

Because of this we-really-ought-to-either-fully-support-bean-val-or-not-support-it-at-all issue, and because MP doesn't officially support Bean Val, I'm leaning towards not supporting it in the MP GraphQL spec.

**Comment by phillip-kruger** [comment]
Ok cool. Also looking at https://github.com/eclipse/microprofile-graphql/issues/68. So we are saying it's up to the vendor. Right ?
Happy to close this then ? Ok ?

**Comment by andymc12** [comment]
Yeah, I think it should be up the vendor - and ideally if the vendors mark fields as non-nullable due to the `@NotNull` bean val annotation, then they would also provide a vendor-specific switch to disable that behavior. That way users will get a 100% compliant and portable behavior if they want to a method marked as `@NotNull` to be nullable in the schema (I cannot think of a use case that would support this, but it's possible that somebody else could).  

I also think that this is something we could change in a future release - especially if bean validation is added to the MP umbrella spec.

**Comment by phillip-kruger** [comment]
Ok thanks, closing this
